formatter: "markdown"

recursive:
  enabled: true
  path: modules

sections:
  show:
    - providers
    - data-sources
    - requirements
    - modules
    - inputs
    - resources
    - outputs

content: |-
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Modules }}
  {{ .Inputs }}
  {{ .Resources }}
  {{ .Outputs }}



output:
  file: terraform-readme.md
  mode: replace
  template: |-
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}

    [//]: # (END_TF_DOCS)

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true